### ISSUE TITLE
Lack of information on the GitHub page - readme, contribution guidelines, changelog, etc.

### ISSUE THREAD

**Issue by JaneSmith** [Yen/PSRT.Astra#11]
First issue! First of all, thanks for this wonderful project. I have some questions and suggestions, and suppose I can break it down into four things:

**1.** The README.md file is almost completely empty. The thread on PSO World contains a screenshot as well as useful information about the project and why one would use it, so couldn't that just be copied into the README file? That would make it a lot easier for people to understand what PSRT Astra is when they visit the GitHub page. _(It'd also be nice to know what "PSRT" actually stands for!)_

**2.** I might be interested in contributing to this project, but I don't see any information at all about that. Usually there would be some details in the README file, or in a separate text file. For example, are contributions even accepted in the first place? Should people ask permission to work on something first, or just go ahead and fork and then send a pull request? Should an issue be opened first to discuss individual contributions before starting work?

**3.** There is a lack of information on the Releases page. All I know is that there was an initial release, then v1.1, and then v1.2 just a short while ago - but what actually changed? To find out, I would have to go through the commit log. It would be greatly appreciated if a changelog could be posted along with each release on the Releases page, to keep everyone informed.

**4.** As there are no previous issues for me to look through and learn from, I'd like to know: how strict are you with regards to the issue tracker? Is it okay to open issues to ask general questions or give general feedback, or should it be strictly reserved for bug reports? Different projects have different stances on this.

Sorry for bombarding you with all those questions. I hope that's okay, and that I'm not intruding or annoying. I'm very interested in this project and have high hopes for it!

**Comment by Yen** [comment]
Hey.

1. This release was me telling someone to release it out of the blue and them posting it on pso-world, didn't really thing about the whole "actual community project" thing. This will be resolved soon with some information that serves to be a more technical version of the forum post (of which I believe a new one is coming).

2. Yeah, I don't really know what to put aside from "contributions welcome" in the README. The pull requests are enabled on the project and so are the issues, as such I welcome both. Ask permission or don't ask permission and have me wake up to my phone pinging at 4AM, its all good. (the latter is probably better as then I only get woken up once). As for if you should open an issue, I think it depends on the size. If its something that is going to have a large impact on the code base it's probably best to simply as a way for others to track your work. Again, it's up to you, at the end of the day you have to submit a PR so we can deal with stuff there.

3. Yeah, the releases have not been that eventful and I need to set up a pipeline so I don't have to zip these up locally. I will try in the future to put more detail into my releases as I would like the github release page to serve as the actual change log for all levels of user.

4. As you have said there are no previous issues. There is also no official support forum for contact (this might have to be a thing if this takes off). Feel free to drop anything that you feel is an _issue_ I guess? As long as its not "how do I enable english patch" its probably fine.

I hope to put most of these in the README and the forum post so this is not the only source of this information.
